### PR TITLE
Dive Page

### PR DESCRIPTION
**Pull request by paskantishubham**
This PR is in ref to #26

### CODE REVIEW

**Comment by paskantishubham** [comment]
Please review [via this link](https://dc-portal-1x.run.aws-usw02-dev.ice.predix.io/v1.2beta/dcsc)  @Pagrawa8 @ajayjoe-nifi 

If needed any changes please comment here.

**Comment by Pagrawa8** [comment]
@paskantishubham, @ayasuda-ge GE @Ripu-D-Singh page looks ok, however we need to review the flow and ensure that we are covering all aspects (what API's and how resource intense). This needs review with PO @mvenukadasula for DIVE

**Comment by ayasuda-ge** [comment]
> @paskantishubham, @ayasuda-ge GE @Ripu-D-Singh page looks ok, however we need to review the flow and ensure that we are covering all aspects (what API's and how resource intense). This needs review with PO @mvenukadasula for DIVE

@mvenukadasula please review [the latest work here](https://dc-portal-1x.run.aws-usw02-dev.ice.predix.io/v1.2beta/dcsc) and share feedback per @Pagrawa8. Thanks!

**Comment by mvenukadasula** [comment]
> > @paskantishubham, @ayasuda-ge GE @Ripu-D-Singh page looks ok, however we need to review the flow and ensure that we are covering all aspects (what API's and how resource intense). This needs review with PO @mvenukadasula for DIVE
> 
> @mvenukadasula please review [the latest work here](https://dc-portal-1x.run.aws-usw02-dev.ice.predix.io/v1.2beta/dcsc) and share feedback per @Pagrawa8. Thanks!

@ayasuda-ge @Pagrawa8 we haven't spent the time in DIVE yet on analyzing what kind of APIs we need to provide and whole dynamic DIVE content.  @Ripu-D-Singh will drive that activity in this sprint and this page can be updated accordingly as we progress.  So you can merge this PR as DIVE changes will come later. CC: @paskantishubham

**Comment by paskantishubham** [comment]
@ayasuda-ge Conflicts are resolved please go ahead and close the PR, Thanks

**Pull request closed without merging**
