### PR TITLE
Thread Connect Service Page

### PR DESCRIPTION
**Pull request by paskantishubham**
This PR is in ref to #14

### CODE REVIEW

**Comment by ayasuda-ge** [comment]
@paskantishubham is the PR reflected in the portal for the review? 

Please review [via this link](https://dc-portal-1x.run.aws-usw02-dev.ice.predix.io/v1.2beta/dcsc)  @Pagrawa8 @ajayjoe-nifi

**Comment by paskantishubham** [comment]
> @paskantishubham is the PR reflected in the portal for the review?
> 
> Please review [via this link](https://dc-portal-1x.run.aws-usw02-dev.ice.predix.io/v1.2beta/dcsc) @Pagrawa8 @ajayjoe-nifi

@ayasuda-ge, yes the changes will be reflected once we restart the server on ng-portal.

**Comment by Pagrawa8** [comment]
@paskantishubham, @ayasuda-ge GE @Ripu-D-Singh page needs a redesign (what API's, how much we want to pull data etc. considerations), based on input from TC PO @ajayjoe-nifi

**Comment by ayasuda-ge** [comment]
> @paskantishubham, @ayasuda-ge GE @Ripu-D-Singh page needs a redesign (what API's, how much we want to pull data etc. considerations), based on input from TC PO @ajayjoe-nifi

Thanks for the input. Understand the re-design. These PRs/Issuers are part of the framework boostrap effort, it changes from time-to-time and portal shan’t be final for a period of time. We will merge it for now. Please open issue trackers for any re-design effort. @Ripu-D-Singh @Pagrawa8 @ajayjoe-nifi

**Review by ajayjoe-nifi — COMMENTED** [review]
Can you add Deepak as the reviewer for TC.

**Comment by ayasuda-ge** [comment]
> Can you add Deepak as the reviewer for TC.

Added per suggested

**Comment by dkrypt** [comment]
File changes look good. There are conflicts with the merge. Please resolve the conflicts and commit again.

**Comment by ayasuda-ge** [comment]
> File changes look good. There are conflicts with the merge. Please resolve the conflicts and commit again.

@paskantishubham  please rebase to resolve the conflict

**Comment by paskantishubham** [comment]
@ayasuda-ge Conflicts are resolved please go ahead and merge, Thanks

**Pull request closed without merging**
