### PR TITLE
Add Service logos on Dashboard

### PR DESCRIPTION
**Pull request by paskantishubham**
This PR is in ref to #24

### CODE REVIEW

**Comment by ayasuda-ge** [comment]
Does the [UI](https://dc-portal-1x.run.aws-usw02-dev.ice.predix.io/v1.2beta/dcsc) look fine for you? @ajayjoe-nifi @Pagrawa8

**Comment by Pagrawa8** [comment]
@paskantishubham, @ayasuda-ge GE @Ripu-D-Singh we need to update the DIVE logo that Ripu created. @mvenukadasula to approve the logo

**Comment by ayasuda-ge** [comment]
> @paskantishubham, @ayasuda-ge GE @Ripu-D-Singh we need to update the DIVE logo that Ripu created. @mvenukadasula to approve the logo

@Ripu-D-Singh please check-in the final logo for development purpose. Thanks!

**Comment by paskantishubham** [comment]
> > @paskantishubham, @ayasuda-ge GE @Ripu-D-Singh we need to update the DIVE logo that Ripu created. @mvenukadasula to approve the logo
> 
> @Ripu-D-Singh please check-in the final logo for development purpose. Thanks!
> 
> @paskantishubham please work with @Ripu-D-Singh to ensure the logo (referred by @Pagrawa8) is committed in your working branch for the merge. Thanks!

@ayasuda-ge Yes I will work on it.

**Comment by Ripu-D-Singh** [comment]
> > @paskantishubham, @ayasuda-ge GE @Ripu-D-Singh we need to update the DIVE logo that Ripu created. @mvenukadasula to approve the logo
> 
> @Ripu-D-Singh please check-in the final logo for development purpose. Thanks!
> 
> @paskantishubham please work with @Ripu-D-Singh to ensure the logo (referred by @Pagrawa8) is committed in your working branch for the merge. Thanks!

Yes, sure, yet to work on final proposals and modifications of DIVE logo, will share with @mvenukadasula , once I get a go ahead will share here.

**Comment by paskantishubham** [comment]
@ayasuda-ge Conflicts are resolved please go ahead and close the PR, Thanks

**Pull request closed without merging**
