### PR TITLE
Develop Dive PMX Page

### PR DESCRIPTION
**Pull request by paskantishubham**
This PR is in ref to #28

### CODE REVIEW

**Comment by paskantishubham** [comment]
Please review [via this link](https://dc-portal-1x.run.aws-usw02-dev.ice.predix.io/v1.2beta/dcsc)  @Pagrawa8 @ajayjoe-nifi 

If needed any changes please comment here.

**Comment by Pagrawa8** [comment]
@paskantishubham, @ayasuda-ge GE @Ripu-D-Singh page looks ok, however we need to review the flow and ensure that we are covering all aspects. This needs review with PO @mvenukadasula for DIVE

**Comment by ayasuda-ge** [comment]
> @paskantishubham, @ayasuda-ge GE @Ripu-D-Singh page looks ok, however we need to review the flow and ensure that we are covering all aspects. This needs review with PO @mvenukadasula for DIVE

@mvenukadasula please review [the latest portal work here](https://dc-portal-1x.run.aws-usw02-dev.ice.predix.io/v1.2beta/dcsc) per @Pagrawa8

**Comment by paskantishubham** [comment]
@ayasuda-ge Conflicts are resolved please go ahead and close the PR, Thanks

**Pull request closed without merging**
